# Generated by Django 4.1.2 on 2022-10-21 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconfig',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='api.config', verbose_name='Конфигурация'),
        ),
        migrations.AlterField(
            model_name='serviceconfig',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.service', verbose_name='Сервис'),
        ),
    ]
